import { CaptionSegment, CaptionStyle, PricingPackage } from '../types';
export { AMHARIC_FONTS, getFontCssStack, type AmharicFontOption } from './fonts';

export const DEFAULT_STYLE: CaptionStyle = {
  preset: 'up',
  font: 'Easy Amharic Typing',
  size: 38,
  color: '#FFFFFF',
  background: 'semi',
  backgroundOpacity: 0.65,
  position: 'bottom',
  outline: 2,
  outlineColor: '#000000',
  highlightWord: true,
  animateIn: 'up',
  animateOut: 'fade',
  animationSpeed: 'normal',
  highlightStyle: 'default',
};

export const STYLE_PRESETS: Record<string, Partial<CaptionStyle>> = {
  up: {
    preset: 'up',
    font: 'Easy Amharic Typing',
    size: 42,
    color: '#FFFFFF',
    background: 'semi',
    backgroundOpacity: 0.75,
    position: 'bottom',
    outline: 2,
    outlineColor: '#0369a1',
    highlightWord: true,
    animateIn: 'up',
    animateOut: 'up',
    animationSpeed: 'normal',
    highlightStyle: 'default',
  },
  down: {
    preset: 'down',
    font: 'Easy Amharic Typing',
    size: 42,
    color: '#FEF08A',
    background: 'solid',
    backgroundOpacity: 0.85,
    position: 'bottom',
    outline: 2,
    outlineColor: '#000000',
    highlightWord: true,
    animateIn: 'down',
    animateOut: 'down',
    animationSpeed: 'normal',
    highlightStyle: 'default',
  },
  'sparkle-duo': {
    preset: 'sparkle-duo',
    font: 'Noto Sans Ethiopic',
    size: 44,
    color: '#F0ABFC',
    background: 'semi',
    backgroundOpacity: 0.65,
    position: 'bottom',
    outline: 3,
    outlineColor: '#38bdf8',
    highlightWord: true,
    animateIn: 'zoom',
    animateOut: 'fade',
    animationSpeed: 'fast',
    highlightStyle: 'sparkle',
  },
  'dotted-selection': {
    preset: 'dotted-selection',
    font: 'Easy Amharic Typing',
    size: 40,
    color: '#A5F3FC',
    background: 'semi',
    backgroundOpacity: 0.8,
    position: 'bottom',
    outline: 1,
    outlineColor: '#0891b2',
    highlightWord: true,
    animateIn: 'fade',
    animateOut: 'fade',
    animationSpeed: 'normal',
    highlightStyle: 'dotted',
  },
  'real-gold': {
    preset: 'real-gold',
    font: 'Noto Serif Ethiopic',
    size: 44,
    color: '#FDE047',
    background: 'solid',
    backgroundOpacity: 0.9,
    position: 'bottom',
    outline: 3,
    outlineColor: '#854d0e',
    highlightWord: true,
    animateIn: 'bounce',
    animateOut: 'fade',
    animationSpeed: 'normal',
    highlightStyle: 'gold',
  },
  'red-string': {
    preset: 'red-string',
    font: 'Easy Amharic Typing',
    size: 42,
    color: '#FFFFFF',
    background: 'solid',
    backgroundOpacity: 0.85,
    position: 'bottom',
    outline: 2,
    outlineColor: '#000000',
    highlightWord: true,
    animateIn: 'up',
    animateOut: 'down',
    animationSpeed: 'fast',
    highlightStyle: 'red-string',
  },
  neon: {
    preset: 'neon',
    font: 'Easy Amharic Typing',
    size: 44,
    color: '#fff',
    background: 'none',
    backgroundOpacity: 0,
    position: 'bottom',
    outline: 1,
    outlineColor: '#ffffff',
    highlightWord: true,
    animateIn: 'zoom',
    animateOut: 'fade',
    animationSpeed: 'normal',
    highlightStyle: 'neon',
  },
  karaoke: {
    preset: 'karaoke',
    font: 'Noto Sans Ethiopic',
    size: 46,
    color: '#ffffff',
    background: 'solid',
    backgroundOpacity: 0.75,
    position: 'bottom',
    outline: 2,
    outlineColor: '#000000',
    highlightWord: true,
    animateIn: 'up',
    animateOut: 'fade',
    animationSpeed: 'normal',
    highlightStyle: 'karaoke',
  },
  typewriter: {
    preset: 'typewriter',
    font: 'Abyssinica',
    size: 38,
    color: '#10b981', // Emerald green
    background: 'semi',
    backgroundOpacity: 0.85,
    position: 'bottom',
    outline: 0,
    outlineColor: '#000000',
    highlightWord: false,
    animateIn: 'none',
    animateOut: 'fade',
    animationSpeed: 'fast',
    highlightStyle: 'default',
  },
  modern: {
    preset: 'modern',
    font: 'Noto Sans Ethiopic',
    size: 36,
    color: '#FFFFFF',
    background: 'semi',
    backgroundOpacity: 0.7,
    position: 'bottom',
    outline: 1,
    outlineColor: '#1e293b',
    animateIn: 'fade',
    animateOut: 'fade',
  },
  bold: {
    preset: 'bold',
    font: 'Easy Amharic Typing',
    size: 44,
    color: '#FACC15', // Vibrant yellow
    background: 'solid',
    backgroundOpacity: 0.9,
    position: 'bottom',
    outline: 3,
    outlineColor: '#000000',
    animateIn: 'up',
    animateOut: 'down',
  },
  tiktok: {
    preset: 'tiktok',
    font: 'Easy Amharic Typing',
    size: 46,
    color: '#FFFFFF',
    background: 'none',
    backgroundOpacity: 0,
    position: 'center',
    outline: 4,
    outlineColor: '#000000',
    animateIn: 'bounce',
    animateOut: 'fade',
  },
  minimal: {
    preset: 'minimal',
    font: 'Abyssinica',
    size: 32,
    color: '#F8FAFC',
    background: 'none',
    backgroundOpacity: 0,
    position: 'bottom',
    outline: 2,
    outlineColor: '#0f172a',
    animateIn: 'fade',
    animateOut: 'fade',
  },
  youtube: {
    preset: 'youtube',
    font: 'Noto Sans Ethiopic',
    size: 38,
    color: '#FFFFFF',
    background: 'solid',
    backgroundOpacity: 0.85,
    position: 'bottom',
    outline: 0,
    outlineColor: '#000000',
    animateIn: 'up',
    animateOut: 'fade',
  },
  classic: {
    preset: 'classic',
    font: 'Noto Serif Ethiopic',
    size: 36,
    color: '#FEF08A',
    background: 'semi',
    backgroundOpacity: 0.6,
    position: 'bottom',
    outline: 1,
    outlineColor: '#78350f',
    animateIn: 'fade',
    animateOut: 'fade',
  },
};

export const INITIAL_PACKAGES: PricingPackage[] = [
  {
    id: 'starter',
    name: 'Starter',
    minutes: 10,
    priceEtb: 25,
    popular: false,
    features: ['10 minutes processing', 'Standard Amharic STT', 'SRT & VTT Export', '720p Video Burn'],
  },
  {
    id: 'creator',
    name: 'Creator',
    minutes: 15,
    priceEtb: 50,
    popular: true,
    features: ['15 minutes processing', 'High Accuracy Amharic STT', 'All Caption Styles', '1080p Video Burn', 'Priority Queue'],
  },
  {
    id: 'pro',
    name: 'Pro',
    minutes: 50,
    priceEtb: 200,
    popular: false,
    features: ['50 minutes processing', 'Maximum STT Accuracy', 'Batch Processing', 'Watermark-free 1080p', 'VIP Support'],
  },
];

// Ge'ez punctuation & common vowels for instant typing keyboard
export const AMHARIC_PUNCTUATION = [
  { char: '፡', name: 'Word space (ሁለት ነጥብ)' },
  { char: '፣', name: 'Comma (ነጠላ ሰረዝ)' },
  { char: '።', name: 'Period (አራት ነጥብ)' },
  { char: '፤', name: 'Semicolon (ድርብ ሰረዝ)' },
  { char: '፥', name: 'Colon (አንቀጽ)' },
  { char: '፦', name: 'Preface colon' },
  { char: '፧', name: 'Question mark' },
];

export const COMMON_AMHARIC_PHRASES = [
  'እንደምን አደራችሁ',
  'እንኳን ደህና መጣችሁ',
  'ዛሬ ስለ አዲሱ ቴክኖሎጂ እንነጋገራለን',
  'ቪዲዮውን ላይክ እና ሰብስክራይብ ማድረግ አትርሱ',
  'አስተያየትዎን ከታች ያጋሩ',
  'በቀጣይ ፕሮግራም እንገናኝ',
  'አመሰግናለሁ',
];

// Sample demo videos that run reliably in any browser with different caption styles
export interface SampleVideo {
  id: string;
  title: string;
  url: string;
  duration: number; // in seconds
  fileSizeMb: number;
  thumbnail: string;
  styleName?: string;
  presetKey?: string;
  aspectRatio?: '9:16' | '16:9' | '1:1';
  platform?: 'tiktok' | 'youtube' | 'instagram' | 'facebook';
  defaultSegments: CaptionSegment[];
}

export const SAMPLE_VIDEOS: SampleVideo[] = [
  {
    id: 'sample-gold',
    title: 'luxury_gold_interview.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration: 154,
    fileSizeMb: 42.5,
    thumbnail: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80',
    styleName: 'Real Gold 👑 (ንፁህ ወርቅ)',
    presetKey: 'real-gold',
    aspectRatio: '9:16',
    platform: 'tiktok',
    defaultSegments: [
      { id: 'seg-1', start: 0.5, end: 3.8, text: 'እንደምን አደራችሁ ክቡራትና ክቡራን።' },
      { id: 'seg-2', start: 4.2, end: 7.9, text: 'ዛሬ ወደ አዲስ የቪዲዮ ይዘት እንኳን ደህና መጣችሁ።' },
      { id: 'seg-3', start: 8.4, end: 12.1, text: 'የዛሬው ርዕሳችን ስለ ዲጂታል ፈጠራ እና ቴክኖሎጂ ነው።' },
      { id: 'seg-4', start: 12.6, end: 16.5, text: 'ይህንን ቪዲዮ እስከ መጨረሻው እንዲከታተሉ እንጋብዛለን።' },
      { id: 'seg-5', start: 17.0, end: 21.2, text: 'አስተያየት ካላችሁ በኮሜንት መስጫው ላይ ጻፉልን።' },
    ],
  },
  {
    id: 'sample-sparkle',
    title: 'viral_sparkle_duo.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration: 312,
    fileSizeMb: 68.2,
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
    styleName: 'Sparkle Duo-O ✦ (አንፀባራቂ)',
    presetKey: 'sparkle-duo',
    aspectRatio: '9:16',
    platform: 'instagram',
    defaultSegments: [
      { id: 'seg-201', start: 0.8, end: 4.5, text: 'ሰላም ጤና ይስጥልኝ ጓደኞቼ እንደምን አላችሁ!' },
      { id: 'seg-202', start: 5.0, end: 9.3, text: 'በዛሬው ቭሎግ በአዲስ አበባ ውብ ስፍራዎች እንዘዋወራለን።' },
      { id: 'seg-203', start: 9.8, end: 14.2, text: 'የኢትዮጵያን ባህላዊ ቡና እና ድንቅ የምግብ ባህል እናያለን።' },
      { id: 'seg-204', start: 14.8, end: 19.5, text: 'አብራችሁን ስላላችሁ ከልብ እናመሰግናለን!' },
    ],
  },
  {
    id: 'sample-red',
    title: 'trending_red_string.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration: 768,
    fileSizeMb: 115.0,
    thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    styleName: 'Red String 🎗️ (ቀይ ክር)',
    presetKey: 'red-string',
    aspectRatio: '9:16',
    platform: 'youtube',
    defaultSegments: [
      { id: 'seg-301', start: 1.0, end: 5.0, text: 'የአርቴፊሻል ኢንተለጀንስ እድገት በኢትዮጵያ ውስጥ።' },
      { id: 'seg-302', start: 5.5, end: 9.8, text: 'የአማርኛ ቋንቋ ሞዴሎች እና የትርጉም ስራዎች ውጤት።' },
      { id: 'seg-303', start: 10.2, end: 15.0, text: 'ለሀገራችን ወጣቶች ሰፊ የስራ እድል ይፈጥራል።' },
      { id: 'seg-304', start: 15.5, end: 19.8, text: 'የፈጠራ ስራዎችን በቀላሉ በቪዲዮ ማጋራት ይቻላል።' },
    ],
  },
  {
    id: 'sample-dotted',
    title: 'cyber_dotted_focus.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    duration: 210,
    fileSizeMb: 52.0,
    thumbnail: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
    styleName: 'Dotted Box ⋮ (ነጠብጣብ)',
    presetKey: 'dotted-selection',
    aspectRatio: '9:16',
    platform: 'tiktok',
    defaultSegments: [
      { id: 'seg-401', start: 0.6, end: 4.2, text: 'ቀጣዩን ትውልድ በዲጂታል እውቀት እናዘጋጅ።' },
      { id: 'seg-402', start: 4.8, end: 8.9, text: 'በአማርኛ ቋንቋ የተሰሩ የቪዲዮ ይዘቶች ተደራሽነት አላቸው።' },
      { id: 'seg-403', start: 9.4, end: 13.8, text: 'በቀላሉ ድምጽዎን ወደ ጽሁፍ ይቀይሩ።' },
    ],
  },
  {
    id: 'sample-up',
    title: 'kinetic_up_elevation.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    duration: 180,
    fileSizeMb: 48.0,
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    styleName: 'Up Kinetic ↑ (ወደላይ)',
    presetKey: 'up',
    aspectRatio: '16:9',
    platform: 'youtube',
    defaultSegments: [
      { id: 'seg-501', start: 0.5, end: 4.0, text: 'ውጤታማ የቪዲዮ ፈጣሪ ለመሆን ዋናው ሚስጥር።' },
      { id: 'seg-502', start: 4.5, end: 8.5, text: 'ተመልካቾች ድምጽ ባይከፍቱም ካፕሽን እንዲያነቡ ማድረግ ነው።' },
      { id: 'seg-503', start: 9.0, end: 13.5, text: 'ይህ የቪዲዮዎን እይታ በሶስት እጥፍ ያሳድገዋል።' },
    ],
  },
];
