import { CaptionSegment, CaptionStyle } from '../types';
import { getFontCssStack } from './fonts';

export function formatTimeSeconds(seconds: number): string {
  if (isNaN(seconds) || seconds < 0) return '00:00';
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  const pad = (n: number) => n.toString().padStart(2, '0');
  
  if (mins >= 60) {
    const hours = Math.floor(mins / 60);
    const remMins = mins % 60;
    return `${pad(hours)}:${pad(remMins)}:${pad(secs)}`;
  }
  return `${pad(mins)}:${pad(secs)}`;
}

export function formatMinutesChange(seconds: number): string {
  const isNegative = seconds < 0;
  const absSecs = Math.abs(seconds);
  const formatted = formatTimeSeconds(absSecs);
  return isNegative ? `-${formatted}` : `+${formatted}`;
}

// Convert seconds to SRT timestamp: 00:00:01,500
export function toSrtTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 1000);
  
  const pad = (n: number, z = 2) => n.toString().padStart(z, '0');
  return `${pad(hours)}:${pad(minutes)}:${pad(secs)},${pad(millis, 3)}`;
}

// Convert seconds to WebVTT timestamp: 00:00:01.500
export function toVttTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 1000);
  
  const pad = (n: number, z = 2) => n.toString().padStart(z, '0');
  return `${pad(hours)}:${pad(minutes)}:${pad(secs)}.${pad(millis, 3)}`;
}

// Generate SRT file text
export function generateSrt(segments: CaptionSegment[]): string {
  const sorted = [...segments].sort((a, b) => a.start - b.start);
  return sorted
    .map((seg, idx) => {
      const index = idx + 1;
      const time = `${toSrtTimestamp(seg.start)} --> ${toSrtTimestamp(seg.end)}`;
      return `${index}\n${time}\n${seg.text.trim()}\n`;
    })
    .join('\n');
}

// Generate WebVTT file text
export function generateVtt(segments: CaptionSegment[]): string {
  const sorted = [...segments].sort((a, b) => a.start - b.start);
  const header = 'WEBVTT - Generated by Amharic Caption Generator\n\n';
  const cues = sorted
    .map((seg, idx) => {
      const time = `${toVttTimestamp(seg.start)} --> ${toVttTimestamp(seg.end)}`;
      return `${idx + 1}\n${time}\n${seg.text.trim()}\n`;
    })
    .join('\n');
  return header + cues;
}

// Helper to trigger file download in browser
export function downloadFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Helper to trigger binary blob download
export function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Client-Side Video Burner Engine
 * Paints video frames + styled Amharic caption onto a hidden canvas and records via MediaRecorder.
 * Supports progress callbacks and cancellation.
 */
export async function burnCaptionsIntoVideo(
  videoElement: HTMLVideoElement,
  segments: CaptionSegment[],
  style: CaptionStyle,
  onProgress?: (percent: number) => void
): Promise<Blob> {
  return new Promise(async (resolve, reject) => {
    try {
      if (document.fonts && document.fonts.ready) {
        await document.fonts.ready;
      }
      const canvas = document.createElement('canvas');
      const width = videoElement.videoWidth || 1280;
      const height = videoElement.videoHeight || 720;
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        throw new Error('Canvas 2D context not supported');
      }

      // Clone or prepare video stream
      const stream = canvas.captureStream(30); // 30 fps
      
      // Try to capture audio if available
      try {
        const audioStream = (videoElement as any).captureStream ? (videoElement as any).captureStream() : null;
        if (audioStream) {
          const audioTracks = audioStream.getAudioTracks();
          if (audioTracks && audioTracks.length > 0) {
            stream.addTrack(audioTracks[0]);
          }
        }
      } catch (err) {
        console.warn('Could not attach audio track:', err);
      }

      const mimeType = MediaRecorder.isTypeSupported('video/mp4;codecs=avc1')
        ? 'video/mp4;codecs=avc1'
        : MediaRecorder.isTypeSupported('video/webm;codecs=vp9')
        ? 'video/webm;codecs=vp9'
        : 'video/webm';

      const recorder = new MediaRecorder(stream, { mimeType, videoBitsPerSecond: 3500000 });
      const chunks: Blob[] = [];

      recorder.ondataavailable = (e) => {
        if (e.data && e.data.size > 0) {
          chunks.push(e.data);
        }
      };

      recorder.onstop = () => {
        const outputBlob = new Blob(chunks, { type: mimeType });
        resolve(outputBlob);
      };

      recorder.onerror = (e) => {
        reject(e);
      };

      recorder.start();

      // Rewind and play to render
      const originalTime = videoElement.currentTime;
      videoElement.currentTime = 0;
      await new Promise((r) => {
        videoElement.onseeked = r;
      });

      let watermarkImg: HTMLImageElement | null = null;
      if (style.watermarkEnabled !== false && style.watermarkImage) {
        watermarkImg = new Image();
        watermarkImg.src = style.watermarkImage;
        await new Promise((resolve) => {
          watermarkImg!.onload = resolve;
          watermarkImg!.onerror = resolve;
        });
      }

      const duration = videoElement.duration || 10;
      videoElement.play();

      let isRendering = true;

      const drawFrame = () => {
        if (!isRendering) return;
        const curTime = videoElement.currentTime;
        const progress = Math.min(100, Math.round((curTime / duration) * 100));
        if (onProgress) onProgress(progress);

        // Draw video frame
        ctx.drawImage(videoElement, 0, 0, width, height);

        // Find active caption segment
        const activeSeg = segments.find(
          (s) => curTime >= s.start && curTime <= s.end
        );

        if (activeSeg && activeSeg.text) {
          drawCaptionOverlay(ctx, activeSeg.text, width, height, style, activeSeg, curTime);
        }

        // Draw Watermark
        if (style.watermarkEnabled !== false) {
          ctx.save();
          ctx.globalAlpha = style.watermarkOpacity ?? 1;
          const pos = style.watermarkPosition || 'top-right';
          const paddingX = 40;
          const paddingY = 40;

          if (watermarkImg && watermarkImg.complete && watermarkImg.naturalHeight !== 0) {
            const wmHeight = Math.max(30, Math.round(height * 0.05));
            const wmWidth = (wmHeight / watermarkImg.naturalHeight) * watermarkImg.naturalWidth;
            let wmX = paddingX;
            let wmY = paddingY;

            if (pos === 'top-right') wmX = width - wmWidth - paddingX;
            else if (pos === 'bottom-left') wmY = height - wmHeight - paddingY - 100;
            else if (pos === 'bottom-right') {
              wmX = width - wmWidth - paddingX;
              wmY = height - wmHeight - paddingY - 100;
            }

            ctx.drawImage(watermarkImg, wmX, wmY, wmWidth, wmHeight);
          } else {
            const wmText = style.watermarkText || 'bgern.com';
            ctx.font = `bold ${Math.max(16, Math.round(width * 0.02))}px sans-serif`;
            ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
            ctx.shadowColor = 'rgba(0, 0, 0, 0.5)';
            ctx.shadowBlur = 4;
            ctx.textAlign = pos.includes('right') ? 'right' : 'left';
            ctx.textBaseline = 'top';

            let txtX = paddingX;
            let txtY = paddingY;

            if (pos === 'top-right') txtX = width - paddingX;
            else if (pos === 'bottom-left') txtY = height - paddingY - 100;
            else if (pos === 'bottom-right') {
              txtX = width - paddingX;
              txtY = height - paddingY - 100;
            }

            ctx.fillText(wmText, txtX, txtY);
          }
          ctx.restore();
        }

        if (videoElement.ended || curTime >= duration - 0.1) {
          isRendering = false;
          recorder.stop();
          videoElement.pause();
          videoElement.currentTime = originalTime;
          if (onProgress) onProgress(100);
        } else {
          requestAnimationFrame(drawFrame);
        }
      };

      requestAnimationFrame(drawFrame);
    } catch (err) {
      reject(err);
    }
  });
}

// Draw caption text onto canvas context with In/Out kinetics and style presets
function drawCaptionOverlay(
  ctx: CanvasRenderingContext2D,
  text: string,
  canvasWidth: number,
  canvasHeight: number,
  style: CaptionStyle,
  activeSeg?: CaptionSegment,
  curTime?: number
) {
  ctx.save();

  // Animation kinetic calculation if activeSeg & curTime are provided
  let displayText = text;
  if (activeSeg && curTime !== undefined && style.preset === 'typewriter') {
    const segDuration = Math.max(0.2, activeSeg.end - activeSeg.start);
    const elapsed = Math.max(0, curTime - activeSeg.start);
    const ratio = Math.min(0.999, elapsed / segDuration);
    const charCount = Math.max(1, Math.floor(ratio * text.length));
    displayText = text.slice(0, charCount);
  }

  // Font calculation relative to canvas width
  const scale = canvasWidth / 800;
  const fontSize = Math.max(20, Math.round(style.size * scale));
  const fontFamilyStack = getFontCssStack(style.font);
  ctx.font = `bold ${fontSize}px ${fontFamilyStack}`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';

  // Calculate position
  let yPos = canvasHeight * 0.84; // bottom default
  if (style.position === 'top') {
    yPos = canvasHeight * 0.16;
  } else if (style.position === 'center') {
    yPos = canvasHeight * 0.5;
  }

  // Animation kinetic calculation if activeSeg & curTime are provided
  if (activeSeg && curTime !== undefined) {
    const elapsed = Math.max(0, curTime - activeSeg.start);
    const remaining = Math.max(0, activeSeg.end - curTime);
    const animSpeed = style.animationSpeed || 'normal';
    const animDuration = animSpeed === 'fast' ? 0.2 : animSpeed === 'slow' ? 0.45 : 0.3;
    const animateIn = style.animateIn || 'up';
    const animateOut = style.animateOut || 'fade';

    if (elapsed < animDuration && animateIn !== 'none') {
      const p = Math.min(1, elapsed / animDuration);
      ctx.globalAlpha = p;
      if (animateIn === 'up') yPos += (1 - p) * 20 * scale;
      else if (animateIn === 'down') yPos -= (1 - p) * 20 * scale;
    } else if (remaining < animDuration && remaining >= 0 && animateOut !== 'none') {
      const p = Math.max(0, remaining / animDuration);
      ctx.globalAlpha = p;
      if (animateOut === 'down') yPos += (1 - p) * 20 * scale;
      else if (animateOut === 'up') yPos -= (1 - p) * 20 * scale;
    }
  }

  const xPos = canvasWidth / 2;
  const metrics = ctx.measureText(displayText);
  const textWidth = metrics.width;
  const paddingX = fontSize * 0.6;
  const paddingY = fontSize * 0.35;
  const boxWidth = textWidth + paddingX * 2;
  const boxHeight = fontSize + paddingY * 2;
  const boxX = xPos - boxWidth / 2;
  const boxY = yPos - boxHeight / 2;
  const radius = 12 * scale;

  const highlight = style.highlightStyle || (
    style.preset === 'sparkle-duo' ? 'sparkle' :
    style.preset === 'dotted-selection' ? 'dotted' :
    style.preset === 'real-gold' ? 'gold' :
    style.preset === 'red-string' ? 'red-string' :
    style.preset === 'karaoke' ? 'karaoke' :
    style.preset === 'neon' ? 'neon' : 'default'
  );

  // Background box if selected or preset has background
  if (style.background === 'semi' || style.background === 'solid' || highlight === 'gold' || highlight === 'dotted') {
    ctx.fillStyle =
      style.background === 'solid'
        ? `rgba(0, 0, 0, ${style.backgroundOpacity ?? 0.85})`
        : `rgba(15, 23, 42, ${style.backgroundOpacity ?? 0.65})`;

    ctx.beginPath();
    ctx.roundRect(boxX, boxY, boxWidth, boxHeight, radius);
    ctx.fill();

    if (highlight === 'gold') {
      ctx.strokeStyle = '#eab308';
      ctx.lineWidth = 1.5 * scale;
      ctx.stroke();
    } else if (highlight === 'dotted') {
      ctx.strokeStyle = '#22d3ee';
      ctx.lineWidth = 2 * scale;
      ctx.setLineDash([6 * scale, 4 * scale]);
      ctx.stroke();
      ctx.setLineDash([]);
    } else if (highlight === 'red-string') {
      ctx.fillStyle = '#ef4444';
      ctx.fillRect(boxX, boxY + boxHeight - 3 * scale, boxWidth, 3 * scale);
    }
  }

  // Neon Glow Effect
  if (highlight === 'neon') {
    ctx.shadowColor = '#ec4899';
    ctx.shadowBlur = 12 * scale;
  }

  // Text Outline / Stroke
  if (style.outline > 0) {
    ctx.strokeStyle = style.outlineColor || '#000000';
    ctx.lineWidth = style.outline * scale * 2;
    ctx.lineJoin = 'round';
    ctx.strokeText(displayText, xPos, yPos);
  }

  // Text Fill
  if (highlight === 'gold') {
    const goldGrad = ctx.createLinearGradient(0, yPos - fontSize / 2, 0, yPos + fontSize / 2);
    goldGrad.addColorStop(0, '#fef08a');
    goldGrad.addColorStop(0.5, '#facc15');
    goldGrad.addColorStop(1, '#ca8a04');
    ctx.fillStyle = goldGrad;
  } else if (highlight === 'sparkle') {
    const duoGrad = ctx.createLinearGradient(boxX, 0, boxX + boxWidth, 0);
    duoGrad.addColorStop(0, '#f472b6');
    duoGrad.addColorStop(0.5, '#c084fc');
    duoGrad.addColorStop(1, '#38bdf8');
    ctx.fillStyle = duoGrad;
  } else if (highlight === 'karaoke') {
    const karaokeGrad = ctx.createLinearGradient(boxX, 0, boxX + boxWidth, 0);
    karaokeGrad.addColorStop(0, '#4ade80');
    karaokeGrad.addColorStop(1, '#a7f3d0');
    ctx.fillStyle = karaokeGrad;
  } else {
    ctx.fillStyle = style.color || '#FFFFFF';
  }

  ctx.fillText(displayText, xPos, yPos);

  ctx.restore();
}
